version: '3'
services:
  ghostinashell1:
    build: .
    image: he2021/ghostinashell1
    restart: always
    networks:
      - challengenet
    ports:
      - "2106:22"
    environment:
      - SSH_USERS=inky:1000:1000
      - SSH_ENABLE_PASSWORD_AUTH=true
    volumes:
      - keys:/etc/ssh/keys
volumes:
  keys:
networks:
  challengenet:
    external: true