version: '3'
services:
  ghostinashell2:
    build: .
    image: he2021/ghostinashell2
    restart: always
    networks:
      - challengenet
    ports:
      - "2108:22"
    environment:
      - SSH_USERS=clyde:1000:1000,pacman:1001:1001
      - SSH_ENABLE_PASSWORD_AUTH=true
    volumes:
      - keys:/etc/ssh/keys
volumes:
  keys:
networks:
  challengenet:
    external: true